(function() {var implementors = {};
implementors['libc'] = [];implementors['hoedown'] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.slice.html'>&amp;'a [</a><a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.u8.html'>u8</a><a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.slice.html'>]</a>&gt; for <a class='struct' href='hoedown/struct.Buffer.html' title='hoedown::Buffer'>Buffer</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;&amp;'a <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>&gt; for <a class='struct' href='hoedown/struct.Buffer.html' title='hoedown::Buffer'>Buffer</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.pointer.html'>*const </a><a class='struct' href='hoedown/ffi/struct.hoedown_buffer.html' title='hoedown::ffi::hoedown_buffer'>hoedown_buffer</a>&gt; for <a class='struct' href='hoedown/struct.Buffer.html' title='hoedown::Buffer'>Buffer</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.pointer.html'>*mut </a><a class='struct' href='hoedown/ffi/struct.hoedown_buffer.html' title='hoedown::ffi::hoedown_buffer'>hoedown_buffer</a>&gt; for <a class='struct' href='hoedown/struct.Buffer.html' title='hoedown::Buffer'>Buffer</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='hoedown/struct.Buffer.html' title='hoedown::Buffer'>Buffer</a>&gt; for <a class='struct' href='hoedown/struct.Markdown.html' title='hoedown::Markdown'>Markdown</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.slice.html'>&amp;'a [</a><a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.u8.html'>u8</a><a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.slice.html'>]</a>&gt; for <a class='struct' href='hoedown/struct.Markdown.html' title='hoedown::Markdown'>Markdown</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
